### ISSUE TITLE
Pyto and Pythonista

### ISSUE THREAD

**Issue by yjqiang** [ColdGrub1384/Pyto#1]
I used Pythonista for a year. 
'Pythonista is a complete development environment for writing Python scripts on your iPad or iPhone.' https://www.python.org/download/other/
So no offence, although I want to try pyto, I wonder why should I use pyto instead of pythonista?

**Comment by ColdGrub1384** [comment]
If you already have Pythonista, you shouldn't try Pyto. Pythonista is better than Pyto but Pyto is open source. My first goal was to make a Python IDE more integrated with the system. The currently available in the AppStore supports the standard file browser from the Files app, like iWork. The user can import more libraries from the  Files app. But new updates were rejected because the app can import scripts from other apps. I submitted a new update with a custom file browser and with less system, integration ;(. I'm waiting Apple to review the app. This update also supports `os.system` with basic commands, so you can code a shell and I don't know if Pythonista supports that.

**Comment by yjqiang** [comment]
Open sourse is wonderful since everyone can contribute to it and make it better. Pythonista has some modules in it like pillow, matplotlib and so on. And there are many other modules, we can use stash(a script made for pythonsita) to install pure python modules.

**Comment by yjqiang** [comment]
And pythonista also has some modules just for ios. I'm using pythonista but I'm happy to try pyto. And I'm looking forward to the new pyto. Thx.
