### ISSUE TITLE
Add a paste button to the top of the onscreen keyboard

### ISSUE THREAD

**Issue by cclauss** [ColdGrub1384/Pyto#31]
I successfully pip installed __static-frame__ and then in the REPL went step-by-step through the tutorial: https://github.com/InvestmentSystems/static-frame

When I wanted to copy new commands from the __static-frame__ tutorial into Pyto, I had to tap the screen at least once and often multiple times before the __paste__ button would pop up.  It would be faster and more convenient if there was a __paste__ button at the top left of the onscreen keyboard.  Also a way to scroll forward and back through previous commands in the REPL history.  Finally the ability to move the cursor in the current command to make edits in the middle of the command before taping return.

**Comment by ColdGrub1384** [comment]
I added a text field in the console, so the text is typed on a separated text area at bottom instead of directly on the console, that would allow moving the cursor etc. I will add buttons on top of the keyboard for browsing history. I will also add a paste button. I will also add a `^C` button for sending `KeyboardInterrupt` (That's currently possible by pressing ^C on a hardware keyboard).

**Comment by ColdGrub1384** [comment]
b35219fc13f096ba544ab4dc3d193ad30d0c8b50 b02bf45b1bcc879c4b61eeecc438c0ac287f8a6a

**Comment by cclauss** [comment]
What about for the on-screen keyboard for the editor? Cut, copy, paste, undo, redo...

**Comment by ColdGrub1384** [comment]
That would left less space for suggestions. I could add undo and redo to the context menu.
