### ISSUE TITLE
sklearn

### ISSUE THREAD

**Issue by nandodmelo** [ColdGrub1384/Pyto#37]
I want to buy the app, i have a question, its possible to install sklearn and quandl?

**Comment by ColdGrub1384** [comment]
It’s possible to install `quandl`, but dependencies aren’t installed automatically so `inflection` and `more_itertools` should be installed manually. They can be installed from `PyPi`.

But, `sklearn` cannot be installed because it has C code and depends on SciPy (which would be very difficult to port to iOS because of Fortran code).
