### ISSUE TITLE
Pandas.read_excel() is missing xlrd for reading excel documents

### ISSUE THREAD

**Issue by jammin0921** [ColdGrub1384/Pyto#41]
Pandas.read_excel() is missing xlrd and I can’t install it manually with pip. Is there a work around? Or is xlrd c-based and can’t use pip for it? Just came across this recently.

**Comment by ColdGrub1384** [comment]
I successfully installed `xlrd` with `pip` and there was no problem. Could you please give me the error message? Or it is something else?

**Comment by jammin0921** [comment]
My mistake. I can install xlrd manually—I wasn’t able to before. I misread the error. 

read_excel() is looking for a path but I just gave it a file name. I don’t think pandas knows which directory it is in and it’s not defaulted to the directory the .py file is in. 

So I need a path for my excel file. Do you know of an easy way to get a path to an excel file on iCloud on iOS?

**Comment by ColdGrub1384** [comment]
To retrieve a file from iCloud Drive, it should be inside the "Pyto" folder due to iOS restrictions. To do it, the script should be in the "Pyto" folder also and the file can be accessed by just writing its name. But, iOS don't let me place a file in this folder, just to create it from Numbers, iOS only allows to put Python scripts inside it.

So, for now, the solution is to place the Excel file in `On My iPhone / iPad > Pyto` and read it like this:

```python
import os.path

excel_path = os.path.expanduser("~/Documents/MyExcelFile.xlsx")
```

**Comment by ColdGrub1384** [comment]
I released an update with a better way to do it. Now, the Excel file can be in any location. You can set a custom directory for a script (it will be saved after re-launch) from the editor. As the File Picker will be presented, the app will have access to the directory. Then, you can access the Excel file by its filename.

**Comment by ColdGrub1384** [comment]
But, if the file is in iCloud Drive or any other cloud storage, it has to be downloaded.
